package com.example.wikibeta_003.LocalDB;

import java.util.Random;

import LocalExceptions.UnimplementedException;

import com.example.wikibeta_003.ECategories;
import com.example.wikibeta_003.Interfaces.ICatagoryListOfArticles;

public class ExampleCatagory implements ICatagoryListOfArticles{

	protected static ICatagoryListOfArticles catagoryListOfArticlesInstance = null;
	protected Random rand = new Random(System.currentTimeMillis());
	
	protected static String[] listOfArticlesNames = {"Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School","Killke culture","Occupational therapy in Seychelles","Piraeus A","Tribunj",
		"Quinebaug Mill – Quebec Square Historic District","Punamusta","Jules de Rohan","Kieran Doherty","Bracken County High School",};
	
	protected ExampleCatagory(){
		//for (String article : listOfArticlesNames) {
		//	articlesNames.add(article);
		//}
	}
	
	public static ICatagoryListOfArticles getCatagory() {
		if (catagoryListOfArticlesInstance == null)
			catagoryListOfArticlesInstance = new ExampleCatagory();
		return catagoryListOfArticlesInstance;
	}

	@Override
	public String getCatagoryName() {
		return "Example";
	}
	
	@Override
	public String getRandomArticle(Boolean noReturn) throws UnimplementedException {
		if (noReturn) throw new UnimplementedException();
		return  listOfArticlesNames[rand.nextInt(listOfArticlesNames.length)];
	}

	@Override
	public ECategories getCatagoryEnum() {
		return ECategories.Example;
	}


}
